import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransiton from "@/components/StairTransiton";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  Weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-JetBrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <Header />
        <StairTransiton/>
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
